# Tests for lucille
# arch-tag: 6670cf71-3b42-4e1d-8251-03ceb402920a
# (c) 2004 Canonical Software Ltd.
# Author: Daniel Silverstone <daniel.silverstone@canonical.com>

.PHONY: all
all:

PYTHONPATH:=$(shell pwd)/../../..
export PYTHONPATH

check: check-lucile

check-lucile:
#	./test_tagfiles.py
#	./test_signedfiles.py
#	./test_utils.py
	./test_domination.py

