#!/bin/sh
# Copyright Canonical Limited
# Author: Daniel Silverstone <daniel.silverstone@canonical.com>

# Buildd Slave tool to apply the ogre model to the chroot

# Expects build id as arg 1, makes build-id to contain the build
# Expects ogre component name as arg 2

# Needs SUDO to be set to a sudo instance for passwordless access
# LN must be an ln instance which can take -s and -f at the same time

SUDO=/usr/bin/sudo

BUILDID="$1"
COMPONENT="$2"

set -e

exec 2>&1

cd $HOME
cd "build-$BUILDID/chroot-autobuild/etc/apt"

echo "Attempting OGRE for $COMPONENT in build-$BUILDID"

if [ -e "sources.list.$COMPONENT" ]; then
  if [ -h "sources.list"]; then
    ln -sf "sources.list.$COMPONENT" sources.list
  else
    echo "OGRE sources.list found, but sources.list is not a symlink"
  fi
else
  echo "No OGRE sources.list found."
fi

