#!/bin/sh
#
# Copyright 2010 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).
#
# Author: Henning Eggers <henning@canonical.com>

# Buildd Slave tool to generate translation templates. Boiler plate code
# copied from sbuild-package.

# Expects build id as arg 1.
# Expects branch url as arg 2.
# Expects output tarball name as arg 3.

# Must run as user with password-less sudo ability.

exec 2>&1

export LANG=C LC_ALL=C

CHMOD=/bin/chmod
CHROOT=/usr/sbin/chroot
CP=/bin/cp
INSTALL=/usr/bin/install
MKDIR=/bin/mkdir
SU=/bin/su
SUDO=/usr/bin/sudo
TOUCH=/usr/bin/touch

BUILDID=$1
BRANCH_URL=$2
RESULT_NAME=$3

BUILDD_HOME=/usr/share/launchpad-buildd
SLAVEBIN=$BUILDD_HOME/slavebin
BUILD_CHROOT="$HOME/build-$BUILDID/chroot-autobuild"
USER=$(whoami)

BUILDD_PACKAGE=canonical/buildd
POTTERY=$BUILDD_PACKAGE/pottery
# The script should be smarter about detecting the python version.
PYMODULES=/usr/lib/pymodules/python2.6

GENERATE_SCRIPT=$PYMODULES/$POTTERY/generate_translation_templates.py

# Copy pottery files to chroot.
$SUDO $MKDIR -p $BUILD_CHROOT$PYMODULES/$BUILDD_PACKAGE
$SUDO $TOUCH $BUILD_CHROOT$PYMODULES/canonical/__init__.py
$SUDO $TOUCH $BUILD_CHROOT$PYMODULES/canonical/buildd/__init__.py
$SUDO $CP -r $BUILDD_HOME/$POTTERY $BUILD_CHROOT$PYMODULES/$BUILDD_PACKAGE
$SUDO $CHMOD -R go+rX $BUILD_CHROOT$PYMODULES/canonical
$SUDO $CHMOD 755 $BUILD_CHROOT$GENERATE_SCRIPT


# Enter chroot, switch back to unprivileged user, execute the generate script.
$SUDO $CHROOT $BUILD_CHROOT \
  $SU - $USER -c "$GENERATE_SCRIPT $BRANCH_URL $RESULT_NAME"
