#!/bin/bash
# Copyright Canonical Limited
# Author: Daniel Silverstone <daniel.silverstone@canonical.com>

# Buildd Slave tool to scan a chroot in case any processes are underneath it

## This script uses bashisms, must be run under bash

# Expects build id as arg 1, makes build-id to contain the build

# Needs SUDO to be set to a sudo instance for passwordless access

SUDO=/usr/bin/sudo
BUILDID="$1"

set -e

exec 2>&1

echo "Scanning for processes to kill in build $BUILDID..."

[ $(id -u) = "0" ] || exec $SUDO $0 "$HOME/build-$BUILDID/chroot-autobuild"

PREFIX="$BUILDID"
FOUND=0

for ROOT in /proc/*/root; do
    LINK=$(readlink $ROOT)
    if [ "x$LINK" != "x" ]; then
	if [ "x${LINK:0:${#PREFIX}}" = "x$PREFIX" ]; then
	    # this process is in the chroot...
	    PID=$(basename $(dirname "$ROOT"))
	    kill -9 "$PID"
	    FOUND=1
	fi
    fi
done

if [ "x$FOUND" = "x1" ]; then
  exec $0 $1
fi
