#!/usr/bin/env python
# Copyright 2010 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).
#
# This is a script to do end-to-end testing of the buildd with a bzr-builder
# recipe, without involving the BuilderBehaviour.

from xmlrpclib import ServerProxy
proxy = ServerProxy('http://localhost:8221/rpc')
print proxy.echo('Hello World')
print proxy.info()
print proxy.status()
recipe_text = """# bzr-builder format 0.2 deb-version something
http://bazaar.launchpad.net/~james-w/bzr-builder/trunk/
merge packaging http://bazaar.launchpad.net/~james-w/bzr-builder/packaging"""
print proxy.build(
    '1-2', 'sourcepackagerecipe', 'f2afc3c0507dffba181638d70ae55ac675679460',
    {}, {'author_name': 'Steve',
         'author_email': 'stevea@example.org',
         'package_name': 'bzr-builder',
         'suite': 'lucid',
         'ogrecomponent': 'universe',
         'purpose': 'puppies',
         'recipe_text': recipe_text,
         'archives': [
            'deb http://nz.archive.ubuntu.com/ubuntu lucid main universe']})
#status = proxy.status()
#for filename, sha1 in status[3].iteritems():
#    print filename
#proxy.clean()
