#!/bin/sh
# Copyright Canonical Limited
# Author: Daniel Silverstone <daniel.silverstone@canonical.com>

# Buildd Slave tool to mount a chroot

# Expects build id as arg 1, makes build-id to contain the build

# Needs SUDO to be set to a sudo instance for passwordless access

SUDO=/usr/bin/sudo
BUILDID="$1"
GREP=/bin/grep
CUT=/usr/bin/cut
XARGS=/usr/bin/xargs

set -e

exec 2>&1

echo "Unmounting chroot for build $BUILDID..."

#$SUDO umount "$HOME/build-$BUILDID/chroot-autobuild/proc"
#$SUDO umount "$HOME/build-$BUILDID/chroot-autobuild/dev/pts"
#$SUDO umount "$HOME/build-$BUILDID/chroot-autobuild/home/buildd/.ccache"
#$SUDO umount "$HOME/build-$BUILDID/chroot-autobuild/var/cache/apt/archives"
$GREP "$HOME/build-$BUILDID/chroot-autobuild" /proc/mounts | \
      $CUT -d\  -f2 | $XARGS -r -n 1 $SUDO umount
