#!/bin/sh
# Copyright Canonical Limited
# Author: Daniel Silverstone <daniel.silverstone@canonical.com>

# Buildd Slave tool to update a debian chroot

# Expects build id as arg 1, makes build-id to contain the build

# Needs SUDO to be set to a sudo instance for passwordless access
# Needs chapt-get to be a chrooted apt-get thingy

SUDO=/usr/bin/sudo
CHAPTGET=/usr/bin/chapt-get
BUILDID="$1"
if [ -f /etc/launchpad-buildd/default ]; then
  eval `grep architecturetag /etc/launchpad-buildd/default | sed 's/ //g'`
fi
if [ -n "$architecturetag" ]; then
  OPTIONS="-o APT::Architecture=$architecturetag"
  if [ "$architecturetag" != "`dpkg --print-installation-architecture`" ]; then
    OPTIONS=$OPTIONS" -o DPkg::Options::=--force-architecture"
  fi
fi

set -e

exec 2>&1

echo "Updating debian chroot for build $BUILDID"

$SUDO $CHAPTGET "$HOME/build-$BUILDID/chroot-autobuild" $OPTIONS -uy update
$SUDO $CHAPTGET "$HOME/build-$BUILDID/chroot-autobuild" $OPTIONS -uy dist-upgrade 

