#!/bin/sh -e

if [ -n "$OVERRIDEROOT" ]
then
    echo "$(date -R): Copying the indices into place."

    INDICES=$ARCHIVEROOT/indices

    mkdir -p -- $INDICES
    rm -f -- $INDICES/override
    cp -- $OVERRIDEROOT/override.* $INDICES/
fi
