#! /bin/bash
#
# Copyright 2009 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).
#
# Check that we have a GeoIP city database.

if [ ! -e /usr/share/GeoIP/GeoLiteCity.dat -a \
     ! -e /usr/share/GeoIP/GeoIPCity.dat ]
  then 
    echo "*********************************************************"
    echo "No GeoIP db found.  Please install launchpad-dependencies"
    echo "*********************************************************"
    exit 1
fi
exit 0
