#!/usr/bin/python2.4
#
# Generates documentation of mapping from remote bug tracker statuses
# to local, Launchpad statuses. Typically, this should be used to
# update the online documentation each time the status mappings are
# updated.
#
# See https://help.launchpad.net/BugStatuses
#

import _pythonpath

from datetime import datetime

from canonical.launchpad.components.externalbugtracker import (
    BUG_TRACKER_CLASSES)


if __name__ == '__main__':
    classes = sorted(BUG_TRACKER_CLASSES.iteritems(),
                     key=lambda (typ, cls): typ.title)

    # Print out a header.
    print '[[Anchor(StatusTables)]]'
    print '== Status mapping tables =='
    print
    print 'Last generated: %s.' % (
        datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC'),)
    print
    print

    for typ, cls in classes:
        # Attempt to find a lookup instance.
        lookup = getattr(cls, '_status_lookup', None)
        if lookup is None:
            continue

        # Find or fabricate titles.
        titles = getattr(cls, '_status_lookup_titles', None)
        if titles is None:
            titles = ['Key %d' % (i + 1) for i in range(lookup.max_depth)]
        else:
            titles = list(titles)
        titles.append('Launchpad status')

        # Print the tables.
        print '[[Anchor(%s)]]' % (typ.name,)
        print '=== %s ===' % (typ.title,)
        print
        for line in lookup.moinmoin_table(titles):
            print line
        print
        print
