#! /bin/sh

# Find the location of your Launchpad
if [ ! -f ~/.rocketfuel ]; then
  echo "You need a file called ~/.rocketfuel containing a single line"
  echo "like:"
  echo "   LAUNCHPAD=~/projects/ubuntu"
  echo "This line should give the location of the top level directory"
  echo "containing your launchpad and config checkouts."
  exit 1
fi
source ~/.rocketfuel

# check that your .rocketfuel file included a line giving the launchpad
# checkout location
if [ ! $LAUNCHPAD ]; then
  echo "Your ~/.rocketfuel file must include a line giving the location"
  echo "of your launchpad directory, of the form"
  echo "LAUNCHPAD=~/projects/ubuntu"
  echo
  echo "Of course, use the correct location for your setup. The"
  echo "directory you specify should at least contain your configs"
  echo "(in a directory called configs) and your launchpad checkout"
  echo "in a directory called launchpad."
  exit 1
fi

if [[ ! "$1" ]]; then
  echo "Usage: launch \"commit message\""
  exit 1
fi

# move into position
cd $LAUNCHPAD/launchpad

# check for loose files
baz status --lint --untagged-files --strict
if [ $? -gt 0 ]; then
  echo "You have untagged files. Please add and commit before refueling."
  exit 1
fi

# then check if there are unmerged changes
baz diff --quiet
if [ $? -gt 0 ]; then
    echo "You've got changes! Please commit them before refueling"
    exit 1
fi;


# run tests
make check
if [ $? -gt 0 ]; then
  echo "Page tests failed, cannot launch."
  exit 1
fi

# mirror archive
baz archive-mirror
if [ $? -gt 0 ]; then
  echo "Archive mirroring failed, cannot launch."
  exit 1
fi

$LAUNCHPAD/arch-pqm/bin/arch-submit-merge "$1" pqm@pqm.ubuntu.com

