#!/usr/bin/env python
import sys
import subprocess

class UserError(Exception):
    pass

def start():
    subprocess.call(
        'sudo tc qdisc add dev lo root netem delay 500ms'.split(' '))

def stop():
    subprocess.call(
        'sudo tc qdisc del dev lo root'.split(' '))

def main(argv):
    commands = {
        'start': start,
        'stop': stop,
    }
    if len(argv) != 1:
        raise UserError('Must supply a command: %s.' %
                        ', '.join(commands.keys()))
    try:
        command = commands[argv[0]]
    except KeyError:
        raise UserError('%s invalid.  Valid commands: %s.' %
                        (argv[1], ', '.join(commands.keys())))
    command()


if __name__ == "__main__":
    try:
        main(sys.argv[1:])
    except UserError, e:
        sys.stderr.write(str(e)+'\n')
