#!/bin/sh

set -e

tempdir=`mktemp -d make-fdoctest.XXXXXX`
listen_port=9000
forward_port=8085

./utilities/tcpwatch/tcpwatch.py -L $listen_port:$forward_port -r $tempdir -s >/dev/null

python lib/zope/app/tests/dochttp.py $tempdir

rm -rf $tempdir

