#! /bin/bash

LP_PROJECT_ROOT=${LP_PROJECT_ROOT:=~/canonical}
LP_BRANCHES_DIR=${LP_BRANCHES_DIR:=lp-branches}
LP_PROJECT_PATH=$LP_PROJECT_ROOT/$LP_BRANCHES_DIR
LP_TRUNK_NAME=trunk
LP_TRUNK_PATH=$LP_PROJECT_PATH/$LP_TRUNK_NAME

# This script pushes each of your branches in your Launchpad repository to
# devpad.canonical.com, assuming your ~/.bazaar/locations.conf has been setup
# correctly by rocketfuel-setup

cd $LP_PROJECT_PATH
for branch in *; do
  if [ ${branch} != "$LP_TRUNK_NAME" ] && test -d ${branch} ; then
    echo "Pushing ${branch}"
    cd ${branch}
    bzr push
    cd ..
  fi;
done;
