#! /bin/bash

#
# Creates a new branch of RF trunk
#

LPBRANCHES="~/canonical/lp-branches"
# force tilde (~) expansion
LPBRANCHES=$(eval echo ${LPBRANCHES})

if [ "x$1" == "x" ]; then 
    echo "Usage: $0 new-branch-name"
    echo "Example: '$0 fixes-bug-54356'"
    exit 2
fi

if [ -e "${LPBRANCHES}/$1" ]; then
    echo "Error: '$1' already exists"
    exit 1
fi

if [ ! -d "${LPBRANCHES}" ]; then
  echo "Error: no rocketfuel found, please run rocketfuel-setup"
  exit 1
fi
cd ${LPBRANCHES}
if [ ! -d trunk ]; then
  echo "Error: no trunk found, please run rocketfuel-setup"
  exit 1
fi

bzr branch trunk $1
cd $1
utilities/link-external-sourcecode ../../lp-sourcedeps
make

