#! /bin/bash
#
# Copyright <YEARS> Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3; see the file LICENSE for

cd `bzr root`

bzr diff -rbranch:../trunk | lsdiff| grep "\.py$" | xargs pyflakes | grep -v "__init__"
cd -

