#! /bin/bash

#
# Creates a new branch of RF trunk
#

LP_PROJECT_ROOT=${LP_PROJECT_ROOT:=~/canonical}
LP_BRANCHES_DIR=${LP_BRANCHES_DIR:=lp-branches}
LP_PROJECT_PATH=$LP_PROJECT_ROOT/$LP_BRANCHES_DIR
LP_TRUNK_NAME=${LP_TRUNK_NAME:=trunk}
LP_TRUNK_PATH=$LP_PROJECT_PATH/$LP_TRUNK_NAME

# force tilde (~) expansion
LP_PROJECT_PATH=$(eval echo ${LP_PROJECT_PATH})

if [ "x$1" == "x" ]; then
    echo "Usage: $0 new-branch-name"
    echo "Example: '$0 fixes-bug-54356'"
    exit 2
fi

if [ -e "${LP_PROJECT_PATH}/$1" ]; then
    echo "Error: '$1' already exists"
    exit 1
fi

if [ ! -d "${LP_PROJECT_PATH}" ]; then
  echo "Error: no rocketfuel found, please run rocketfuel-setup"
  exit 1
fi
cd ${LP_PROJECT_PATH}
if [ ! -d $LP_TRUNK_NAME ]; then
  echo "Error: no trunk found, please run rocketfuel-setup"
  exit 1
fi

bzr branch $LP_TRUNK_NAME $1
cd $1
utilities/link-external-sourcecode
make
