#! /bin/bash

# Check each of the branches in $LP_PROJECT_PATH and show which of them have
# uncommitted changes, also check which ones have revisions that have not yet
# landed on trunk.

utilities_dir="$(cd $(dirname $0) && pwd)"
source "$utilities_dir/rocketfuel-env.sh"

cd $LP_PROJECT_PATH
for branch in *; do
  if [ ${branch} != "$LP_TRUNK_NAME" ] && test -d ${branch} ; then
    echo "Examining ${branch}"
    cd ${branch}
    bzr status --short
    cd $LP_TRUNK_PATH
    bzr missing --theirs-only --line ../${branch} | grep -v "^You are missing"
    cd ..
  fi;
done;
