#! /bin/bash

SOURCEDEPS="~/canonical/lp-sourcedeps/sourcecode"

# Force tilde expansion
SOURCEDEPS=$(eval echo ${SOURCEDEPS})

DEVPAD="devpad.canonical.com"
ROCKETFUELDEPS="/code/rocketfuel-built/launchpad/sourcecode/*"
RSYNCOPTIONS="-avp --partial --progress --delete"

# Make sure we have an ssh key primed
ssh-add -l
if [ $? -gt 0 ]; then ssh-add; fi

# Pull from devpad trunk
cd ~/canonical/lp-branches/trunk
INITIAL_REV=$(bzr revno)
bzr pull
FINAL_REV=$(bzr revno)

# Exit if there are no new revisions
if [ $FINAL_REV = $INITIAL_REV ]; then exit 0; fi


# Update the source dependencies
if [ ! -d $SOURCEDEPS ]; then mkdir -p $SOURCEDEPS; fi

rsync $RSYNCOPTIONS $DEVPAD:$ROCKETFUELDEPS $SOURCEDEPS/

cd ~/canonical/lp-branches
for branch in *; do
  if [ -d $branch/sourcecode ]
  then
    echo "Updating sourcecode dependencies for ${branch}"
    trunk/utilities/link-external-sourcecode --target=$branch --parent=../lp-sourcedeps
  fi
done

cd trunk
make
