#! /bin/bash

# Push all of your branches to devpad, so that you have a server-side backup
# of everything, assuming your ~/.bazaar/locations.conf has been setup
# correctly by rocketfuel-setup.

source "$HOME/.rocketfuel-env.sh"

cd $LP_PROJECT_PATH
for branch in *; do
  if [ ${branch} != "$LP_TRUNK_NAME" ] && test -d ${branch} ; then
    echo "Pushing ${branch}"
    cd ${branch}
    bzr push
    cd ..
  fi;
done;
