#! /bin/bash
#
# Copyright 2009 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

cd `bzr root`

bzr diff -rbranch:../trunk | lsdiff| grep "\.py$" | xargs pyflakes | grep -v "__init__"
cd -

