#! /bin/bash

#
# This script will setup a brand new Ubuntu machine as a LP developer
# workstation, from scratch. The script lives in the LP codebase itself,
# as utilities/rocketfuel-setup
#

# load up Ubuntu release details so we know which repos to enable
source /etc/lsb-release

# Establish Canonical username
whoami=`whoami`
printf "What is your username on Canonical servers? [$whoami] "
read canusrname
if [ ! -z ${canusrname} ]; then
  whoami=${canusrname};
fi

# Test that we can access Canonical servers
ssh ${whoami}@chinstrap.canonical.com pwd > /dev/null
if [ $? -ne 0 ]; then
  echo "
ERROR: Unable to login to chinstrap, please check your Canonical account
details.
"
  exit 1
fi

# Make sure you have all the needed virtual hosts

dev_host() {
  grep -q "^127.0.0.88.*${hostname}" /etc/hosts
  if [ $? -ne 0 ]; then
    sudo sed -i "s/^127.0.0.88.*$/&\ ${hostname}/" /etc/hosts
    echo "${hostname} added to /etc/hosts"
  fi
  }

echo "Checking development hosts"
grep -q "^127.0.0.88" /etc/hosts
if [ $? -ne 0 ]; then
  echo "
# Launchpad virtual domains. This should be on one line.
127.0.0.88      launchpad.dev
" | sudo tee -a /etc/hosts
  echo "launchpad.dev added to /etc/hosts"
fi

for hostname in code.launchpad.dev answers.launchpad.dev blueprints.launchpad.dev bugs.launchpad.dev translations.launchpad.dev xmlrpc.launchpad.dev shipit.ubuntu.dev shipit.kubuntu.dev shipit.edubuntu.dev; do
  dev_host;
done

# Enable relevant Ubuntu package repositories
grep -q "^deb http:.* ${DISTRIB_CODENAME} .*universe" /etc/apt/sources.list
if [ $? -ne 0 ]; then
    echo "Please enable the 'universe' component in /etc/apt/source.list'"
    exit 1
fi
grep -q "^deb http:.* ${DISTRIB_CODENAME} .*multiverse" /etc/apt/sources.list
if [ $? -ne 0 ]; then
    echo "Please enable the 'multiverse' component in /etc/apt/source.list'"
    exit 1
fi

echo "Checking ~/.ssh/config for relevant Canonical hosts"
if [ ! -e ~/.ssh/config ]; then
    touch ~/.ssh/config
fi

grep "^Host .*chinstrap" ~/.ssh/config
if [ $? -ne 0 ]; then
  echo "Host chinstrap chinstrap.canonical.com chinstrap.ubuntu.com
    ForwardAgent yes
    Hostname chinstrap.canonical.com
    ProxyCommand none
    User ${whoami}

" | tee -a ~/.ssh/config > /dev/null
  echo "Added chinstrap to ~/.ssh/config"
fi

grep "^Host.*\*\.canonical.com" ~/.ssh/config
if [ $? -ne 0 ]; then
  echo "Host *.canonical.com *.ubuntu.com
    ForwardAgent yes
    ProxyCommand ssh chinstrap.canonical.com nc -q0 %h %p
    User ${whoami}

" | tee -a ~/.ssh/config > /dev/null
  echo "Added *.canonical.com to ~/.ssh/config"
fi

grep "^Host .*devpad" ~/.ssh/config
if [ $? -ne 0 ]; then
  echo "Host devpad devpad.canonical.com
    ForwardAgent yes
    Hostname devpad.canonical.com
    ProxyCommand ssh chinstrap.canonical.com nc -q0 %h %p
    User ${whoami}

" | tee -a ~/.ssh/config > /dev/null
  echo "Added devpad to ~/.ssh/config"
fi

echo "Testing ssh to devpad..."
ssh devpad.canonical.com pwd > /dev/null
if [ $? -ne 0 ]; then
  echo "
ERROR: Unable to verify capability to ssh to devpad. Please check
~/.ssh/config and uncomment the User configuration, and set the
<canonical-username> to your username on Canonical servers, if it
is not '${whoami}'
"
  exit 1
fi


echo "Retrieving signing-key for LP package repository."
scp devpad.canonical.com:/code/lp-maintainers.pub /tmp/
if [ $? -ne 0 ]; then
  echo "Unable to fetch key for LP package repository"
  exit 1
fi
[ `sha1sum /tmp/lp-maintainers.pub | cut -d " " -f 1` = \
   f1714a57bd8c481f45b2a64e2eb9131176c8922e ] \
&& sudo apt-key add /tmp/lp-maintainers.pub
if [ $? -ne 0 ]; then
  echo "Unable to add key for LP package repository"
  exit 1
fi


echo "Adding LP package respository to package source list."
grep "^deb http://lpdebs.canonical.com/" /etc/apt/sources.list
if [ $? -ne 0 ]; then
  echo "deb http://lpdebs.canonical.com/${DISTRIB_CODENAME} ./" | sudo tee -a /etc/apt/sources.list > /dev/null
  sudo aptitude update
fi


echo "Installing Launchpad developer dependencies..."
sudo aptitude install launchpad-developer-dependencies
if [ $? -ne 0 ]; then
  echo "Unable to install LP developer dependencies"
  exit 1
fi


echo "
<VirtualHost 127.0.0.88:80>
  ServerName launchpad.dev
  ServerAlias *.launchpad.dev
  <Proxy *>
    Order deny,allow
    Allow from 127.0.0.0/255.0.0.0
  </Proxy>
  ProxyPreserveHost on
  ProxyPass / http://localhost:8086/ retry=1
</VirtualHost>
" | sudo tee /etc/apache2/sites-available/launchpad.dev > /dev/null

sudo a2enmod proxy
if [ $? -ne 0 ]; then
  echo "ERROR: Unable to enable proxy module in Apache2"
  exit 1
fi

sudo a2enmod proxy_http
if [ $? -ne 0 ]; then
  echo "ERROR: Unable to enable proxy_http module in Apache2"
  exit 1
fi

sudo a2ensite launchpad.dev
if [ $? -ne 0 ]; then
  echo "ERROR: Unable to enable launchpad.dev"
  exit 1
fi

sudo apache2ctl restart
if [ $? -ne 0 ]; then
  echo "ERROR: Unable to restart Apache2"
  exit 1
fi


echo "Setting up devpad repository"
ssh devpad.canonical.com ~mark/devpad-setup

