#!/usr/bin/python2.4
#
# Copyright 2009 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

"""Update the sourcecode managed in sourcecode/."""

import _pythonpath

import sys

from devscripts import sourcecode


if __name__ == '__main__':
    sys.exit(sourcecode.main(sys.argv))
