# Copyright 2010 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

"""The innards of the Bug Heat cronscript."""

__metaclass__ = type
__all__ = []


class BugHeatCalculator:
    """A class to calculate the heat for a bug."""

    def __init__(self, bug):
        self.bug = bug

    def _getHeatFromPrivacy(self):
        """Return the heat generated by the bug's `private` attribute."""
        if self.bug.private:
            return 150
        else:
            return 0

    def _getHeatFromSecurity(self):
        """Return the heat generated if the bug is security related."""
        if self.bug.security_related:
            return 250
        else:
            return 0

    def _getHeatFromDuplicates(self):
        """Return the heat generated by the bug's duplicates."""
        return self.bug.number_of_duplicates * 6

    def _getHeatFromAffectedUsers(self):
        """Return the heat generated by the bug's affected users."""
        return self.bug.users_affected_count * 4

    def _getHeatFromSubscribers(self):
        """Return the heat generated by the bug's subscribers."""
        direct_subscribers = self.bug.getDirectSubscribers()
        subscribers_from_dupes = self.bug.getSubscribersFromDuplicates()

        return (
            (len(direct_subscribers) + len(subscribers_from_dupes)) * 2)


class BugHeatUpdater:
    """Takes responsibility for updating bug heat."""

    def __init__(self, transaction, logger):
        self.transaction = transaction
        self.logger = logger
