#!/bin/sh

# Post install script

set -e
set -u

USER=${BUILDD_USER:-buildd}
BUILDDGID=${BUILDD_GID:-2501}
BUILDDUID=${BUILDD_UID:-2001}

make_buildd()
{
 buildd-genconfig --name=default --host=0.0.0.0 --port=8221 > \
  /etc/launchpad-buildd/default
 echo Default buildd created.
}

case "$1" in
    configure)
	getent group buildd >/dev/null 2>&1 ||
                addgroup --gid $BUILDDGID buildd

	getent passwd buildd >/dev/null 2>&1 ||
        adduser --ingroup buildd --disabled-login --gecos 'Buildd user' \
                --uid $BUILDDUID ${USER}

        grep -q ^${USER} /etc/sudoers ||
                echo "${USER}  ALL=(ALL) NOPASSWD: ALL" >>/etc/sudoers

        install -d -o${USER} -m0755 /home/${USER}

	# Create ~buildd/.sbuildrc if needed
	if [ ! -f /home/${USER}/.sbuildrc ]; then
	    cp  /usr/share/launchpad-buildd/sbuildrc \
		/home/${USER}/sbuildrc.tmp
	    cd /home/${USER}
	    sed -e's/@ARCHTAG@/'$(dpkg --print-installation-architecture)'/g' \
		-e's/@FQDN@/'$(hostname --fqdn)'/g' \
		<sbuildrc.tmp > .sbuildrc
	    chown $USER:buildd .sbuildrc
	    chmod 0644 .sbuildrc
	    rm sbuildrc.tmp
	fi

	# Prepare a default buildd...
	test -e /etc/launchpad-buildd/default || make_buildd

	# Create any missing directories and chown them appropriately
	test -d /home/${USER}/filecache-default || mkdir /home/${USER}/filecache-default
	chown $USER:buildd /home/${USER}/filecache-default
	test -d /home/${USER}/ccache || mkdir /home/${USER}/ccache
	chown $USER:buildd /home/${USER}/ccache

	chown $USER:buildd /var/log/launchpad-buildd /var/run/launchpad-buildd

	# Check for the presence of the /etc/source-dependencies file
	# which sbuild will rant about the absence of...
	test -e /etc/source-dependencies || touch /etc/source-dependencies

	# Now check if we're upgrading a previous version...
	if [ "x$2" != "x" ]; then
	    for CONFIG in $(ls /etc/launchpad-buildd/* \
	                  | grep -v "^-" | grep -v "~$"); do
		/usr/share/launchpad-buildd/upgrade-config $2 $CONFIG
	    done
	fi

	;;
    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
