#!/bin/sh
#
# Copyright 2010 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

# Pre install script

set -e
set -u

BUILDLOG=/home/buildd/filecache-default/buildlog

# if we have buildlog, and buildd has a twistd process, then there is a build in
# progress.  Let that finish.
if test -e $BUILDLOG && pgrep -u buildd twistd >/dev/null; then
	echo Build in progress, refusing to upgrade. >&2
	echo Set the builder to MANUAL and wait for the current build to finish. >&2
	exit 1
fi

exit 0
