#!/bin/bash

# Archive Contents files generator.
#
# It uses scripts/ftpmaster-tools/lp-query-distro.py script to
# collect up-to-date information about the Ubuntu distribution from
# Launchpad, then sets up an auxiliary archive and a set of
# configuration files to run apt-ftparchive generating Contents
# files for all supported suites.
#

set -x
set -e
set -u

# share lockfile with cron.daily
LOCKFILE=/srv/launchpad.net/ubuntu-archive/cron.daily.lock

# main archive path (target)
ARCHIVE='/srv/launchpad.net/ubuntu-archive'

# auxiliary archive where the contents will be generated (source)
CONTENTARCHIVE='/srv/launchpad.net/ubuntu-contents'

LPPATH='/srv/launchpad.net/codelines/current'
LPCONTENT="$LPPATH/cronscripts/publishing/gen-contents"

# apt-ftparchive configuration file destination
APTCONF_HEADER_TEMPLATE="apt_conf_header.template"
APTCONF_DIST_TEMPLATE="apt_conf_dist.template"
APTCONF="apt-contents.conf"
CONTENTHEADER="Contents.top"

# target suites ()
suites=`$LPPATH/scripts/ftpmaster-tools/lp-query-distro.py supported`

# target architectures for the development series
devel=`$LPPATH/scripts/ftpmaster-tools/lp-query-distro.py development`
archs=`$LPPATH/scripts/ftpmaster-tools/lp-query-distro.py -s $devel archs`

# target components
components='main restricted universe multiverse'

# directories to be pre-created when setting up a fresh tree
dirs='source debian-installer'
for i in $archs; do dirs="$dirs binary-$i"; done

GENERATEFILES="yes"
COMPAREFILES="yes"
MOVEFILES="yes"

set -e

# claim the lock
if ! lockfile -r1 $LOCKFILE; then
  echo "Could not claim lock file."
  exit 1
fi

cleanup () {
  echo "Cleaning up lockfile."
  rm -f $LOCKFILE
}

trap cleanup EXIT

echo 'Ensure we have a private tree in place ...'
mkdir -p $CONTENTARCHIVE/ubuntu-misc
mkdir -p $CONTENTARCHIVE/ubuntu-cache

cp $LPCONTENT/$APTCONF_HEADER_TEMPLATE $CONTENTARCHIVE/ubuntu-misc/$APTCONF
for suite in $suites; do
  sed -e "s/\$SUITE/$suite/g" -e "s/\$ARCHS/$archs/g" \
       $LPCONTENT/$APTCONF_DIST_TEMPLATE >> $CONTENTARCHIVE/ubuntu-misc/$APTCONF
  for component in $components; do
    for dir in $dirs; do
      path="$CONTENTARCHIVE/ubuntu/dists/$suite/$component/$dir"
      if test ! -d $path; then
        echo "   $path"
        mkdir -p $path
      fi
    done
  done
done

if test $GENERATEFILES = "yes" ; then
   echo 'Running apt in your private tree to generate new contents ...'
   cp -a $ARCHIVE/ubuntu-overrides $CONTENTARCHIVE/
   cp $LPCONTENT/$CONTENTHEADER $CONTENTARCHIVE/ubuntu-misc/
   apt-ftparchive generate $CONTENTARCHIVE/ubuntu-misc/$APTCONF
else
   echo "Skipping apt-ftparchive run"
fi


if test $COMPAREFILES = "yes" ; then
  echo 'Comparing contents files with public tree ...'
  for suite in $suites; do
    for arch in $archs; do
      last_contents="$CONTENTARCHIVE/ubuntu/dists/$suite/.Contents-$arch"
      current_contents="$CONTENTARCHIVE/ubuntu/dists/$suite/Contents-$arch"
      new_contents="$CONTENTARCHIVE/ubuntu/dists/$suite/Contents-$arch.gz"
      contents_dest="$ARCHIVE/ubuntu/dists/$suite/Contents-$arch.gz"
      # we don't want to overwrite existing files because they are
      # precious and mirrors would need to refetch them.
      if ! cmp -s $current_contents $last_contents; then
        if test $MOVEFILES = "yes"; then
          echo "   installing new Contents file for $suite/$arch"
          # update cached plain content
          mv "$current_contents" "$last_contents"
          # update real gzipped Content
          mv "$new_contents" "$contents_dest"
          chmod ug=rw,o=r "$contents_dest"
        else
          echo "   not Installing updated Contents file for $suite/$arch"
        fi
      else
          echo "   skipping unmodified Contents file for $suite/$arch"
      fi
    done
  done
else
  echo 'Skipping update of contents files in public tree ...'
fi

