# arch-tag: 6773f9cf-f527-48bb-8521-7a103f106633

default:
	@ echo "Okay, this makefile _was_ crack."
	@ echo "The one in the 'schema' directory is what you want."
	@ echo "Note that one assumes you have already installed postges"
	@ echo "and created a user which can create new databases."
