#!/usr/bin/python

import sys
import os
import PIL.Image

output_name = sys.argv[1]
sources = sys.argv[2:]

output = open(output_name, 'w')

for name in sources:
    image = PIL.Image.open(name)
    print >> output, '%s %dx%d' % ((name,) + image.size)
