#!/usr/bin/python
#
# Copyright 2009 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

import sys
import os
import PIL.Image

output_name = sys.argv[1]
sources = sys.argv[2:]

output = open(output_name, 'w')

for name in sources:
    image = PIL.Image.open(name)
    print >> output, '%s %dx%d' % ((name,) + image.size)
