#!/bin/sh
#
# Copyright 2009 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

SRV=/srv/archive.ubuntu.com

createdb katie2

psql katie2 < $SRV/projectb.dump

echo 'drop database katie; create database katie with template katie2; drop database katie2' | psql template1

