#!/bin/sh

SRV=/srv/archive.ubuntu.com

createdb katie2

psql katie2 < $SRV/projectb.dump

echo 'drop database katie; create database katie with template katie2; drop database katie2' | psql template1

