# Copyright 2009 Canonical Ltd.  All rights reserved.
# pylint: disable-msg=E0211,E0213

"""IHasBuildRecords interface.

Implemented by any object that can have `IBuild` records related to it.
"""

__metaclass__ = type

__all__ = [
    'IHasBuildRecords',
    ]

from zope.interface import Interface
from zope.schema import Choice, TextLine

from canonical.launchpad import _
from canonical.lazr.enum import DBEnumeratedType
from canonical.lazr.rest.declarations import (
    REQUEST_USER, call_with, export_read_operation, operation_parameters,
    operation_returns_collection_of, rename_parameters_as)


class IHasBuildRecords(Interface):
    """An Object that has build records"""

    @rename_parameters_as(name="source_name")
    @operation_parameters(
        name=TextLine(title=_("Source package name"), required=False),
        build_state=Choice(
            title=_('Build status'), required=False,
            description=_('The status of this build record'),
            # Really a BuildStatus see _schema_circular_imports.
            vocabulary=DBEnumeratedType),
        pocket=Choice(
            title=_("Pocket"), required=False, readonly=True,
            description=_("The pocket into which this entry is published"),
            # Really a PackagePublishingPocket see _schema_circular_imports.
            vocabulary=DBEnumeratedType))
    @call_with(user=REQUEST_USER)
    # Really a IBuild see _schema_circular_imports.
    @operation_returns_collection_of(Interface)
    @export_read_operation()
    def getBuildRecords(build_state=None, name=None, pocket=None,
                        user=None):
        """Return build records owned by the object.

        The optional 'build_state' argument selects build records in a specific
        state. This excludes the build records generated by Gina by selecting
        a null datebuilt when buildstate is FULLYBUILT. Results are ordered
        by descending datebuilt. NEEDSBUILD records are special, they are
        ordered by descending BuildQueue.lastscore.  If the optional 'name'
        argument is passed try to find only those builds which the
        sourcepackagename matches (SQL LIKE).
        If pocket is specified return only builds for this pocket, otherwise
        return all.
        "user" is the requesting user and if specified can be used in
        permission checks to see if he is allowed to view the build.
        """
