SET client_min_messages=ERROR;

-- Submissions for the hardware database.

CREATE TABLE HWSystemFingerprint (
    id serial PRIMARY KEY,
    -- An identifier for a system. 
    fingerprint text NOT NULL
        CONSTRAINT hwsystemfingerprint__fingerprint__key UNIQUE
);

CREATE TABLE HWSubmission (
    id serial PRIMARY KEY,

    -- Date and time of the submission. The value is sent by the HWDB client.
    date_created timestamp NOT NULL,

    -- Date and time of the submission. Created by Launchpad during upload.
    date_submitted timestamp NOT NULL,

    -- Submission format as per enum
    format integer NOT NULL,

    -- Status of the data as per enum
    status integer NOT NULL,

    -- True:  The submitter allows public access to the data.
    -- False: The submitter does not allow public access to the data.
    private boolean NOT NULL,

    -- True:  The submitter agrees to be contacted by package maintainers
    --        for tests and similar purposes.
    -- False: The submitter does not want to be contacted,
    contactable boolean NOT NULL,

    -- True:  The submission data originates from a Live CD run.
    -- False: The submission data originates from an regular Ubuntu (or
    --        other Linux) installation
    live_cd boolean NOT NULL DEFAULT false,

    -- A unique submission ID. Generated by the client.
    submission_id text
        CONSTRAINT hwsubmission__submission_id__key UNIQUE NOT NULL,

    -- The ID of the person who submitted the data.
    owner integer NOT NULL
        CONSTRAINT hwsubmission__owned__fk
        REFERENCES Person(id),

    -- The ID of a distroarchseries. The HWDB client submits values for 
    -- distribution, distroseries and architecture. If no distroarchseries
    -- is known for the submitted values, the column value is NULL.
    distroarchseries integer
        CONSTRAINT hwsubmission__distroarchseries__fk
        REFERENCES DistroArchRelease(id),

    -- A reference to a library file alias of the submitted raw data.
    raw_submission integer NOT NULL
        CONSTRAINT hwsubmission__raw_submission__fk
        REFERENCES LibraryFileAlias(id),

    -- A reference to the HWSystemFingerprint table.
    system_fingerprint integer NOT NULL
        CONSTRAINT hwsubmission__system_fingerprint__fk
        REFERENCES HWSystemFingerprint(id)
);

CREATE INDEX hwsubmission__status__idx ON HWSubmission(status);
CREATE INDEX hwsubmission__owner__idx ON HWSubmission(owner);
CREATE INDEX hwsubmission__raw_submission__idx 
    ON HWSubmission(raw_submission);
CREATE INDEX hwsubmission__system_fingerprint__idx
    ON HWSubmission(system_fingerprint);

INSERT INTO LaunchpadDatabaseRevision VALUES (87, 46, 0);
