SET client_min_messages=ERROR;

ALTER TABLE TranslationMessage
RENAME is_current TO is_current_ubuntu;
ALTER TABLE TranslationMessage
RENAME is_imported TO is_current_upstream;

ALTER INDEX tm__potmsgset__language__no_variant__shared__current__key
RENAME TO tm__potmsgset__language__no_variant__shared__ubuntu__key;

ALTER INDEX tm__potmsgset__language__no_variant__shared__imported__key
RENAME TO tm__potmsgset__language__no_variant__shared__upstream__key;

ALTER INDEX tm__potmsgset__language__variant__shared__current__key
RENAME TO tm__potmsgset__language__variant__shared__ubuntu__key;

ALTER INDEX tm__potmsgset__language__variant__shared__imported__key
RENAME TO tm__potmsgset__language__variant__shared__upstream__key;

ALTER INDEX tm__potmsgset__potemplate__language__no_variant__diverged__curr
RENAME TO tm__potmsgset__template__language__no_variant__diverged__ubuntu__key;

ALTER INDEX tm__potmsgset__potemplate__language__no_variant__diverged__impo
RENAME TO tm__potmsgset__template__language__no_variant__diverged__upstream__key;

ALTER INDEX tm__potmsgset__potemplate__language__variant__diverged__current
RENAME TO tm__potmsgset__template__language__variant__diverged__ubuntu__key;

ALTER INDEX tm__potmsgset__potemplate__language__variant__diverged__importe
RENAME TO tm__potmsgset__template__language__variant__diverged__upstream__key;

ALTER INDEX translationmessage__language__no_variant__submitter__idx
RENAME TO tm__language__no_variant__submitter__idx;

ALTER INDEX translationmessage__language__variant__submitter__idx
RENAME TO tm__language__variant__submitter__idx;

-- XXX: Update patch number!
INSERT INTO LaunchpadDatabaseRevision VALUES (2208, 99, 0)
