-- Submissions for the hardware database.

CREATE TABLE HWDBSystemFingerprint (
    id serial PRIMARY KEY,
    -- An identifier for a system. 
    fingerprint text NOT NULL UNIQUE
);

CREATE TABLE HWDBSubmission (
    id serial PRIMARY KEY,
    -- Date and time of the submission. The value is sent by the HWDB client.
    date_created timestamp NOT NULL,
    -- Date and time of the submission. Created by Launchpad during upload.
    date_submitted timestamp NOT NULL,
    -- Submission format.
    format integer NOT NULL,
    -- Status of the data.
    --   1: not parsed
    --   0: invalid data
    --   other values: not yet defined.
    status integer NOT NULL,
    -- True:  The submitter allows public access to the data.
    -- False: The submitter does not allow public access to the data.
    private boolean NOT NULL,
    -- True:  The submitter agrees to be contacted by package maintainers
    --        for tests and similar purposes.
    -- False: The submitter does not want to be contacted,
    contactable boolean NOT NULL,
    -- True:  The submission data originates from a Live CD run.
    -- False: The submission data originates from an regular Ubuntu (or
    --        other Linux) installation
    live_cd boolean NOT NULL DEFAULT false,
    -- A unique submission ID. Generated by the client.
    submission_id text UNIQUE NOT NULL,
    -- The ID of the person who submitted the data.
    owner integer REFERENCES Person(id) NOT NULL,
    -- The ID of a distroarchrelease. The HWDB client submits values for 
    -- distribution, distrorelease and architecture. If no distroarchrelease
    -- is known for the submitted values, the column value is NULL.
    distroarchrelease integer REFERENCES Distroarchrelease(id),
    -- A reference to a library file alias of the submitted raw data.
    raw_submission integer NOT NULL REFERENCES LibraryFileAlias(id),
    -- A reference to the HWDBSystemFingerprint table.
    system_fingerprint integer NOT NULL REFERENCES HWDBSystemFingerprint(id),
    emailaddress text
);

CREATE INDEX HWDVSubmission__status__idx ON HWDBSubmission(status);
CREATE INDEX HWDBSubmission__owner__idx ON HWDBSubmission(owner);
CREATE INDEX HWDBSubmission__raw_submission__idx 
    ON HWDBSubmission(raw_submission);
CREATE INDEX HWDBSubmission__system_fingerprint__idx
    ON HWDBSubmission(system_fingerprint);
