#!/bin/sh
#
# launchpad-buildd-sequencer
#               This file is used to start and stop launchpad buildd
#               sequencer
#
# Author:       Celso Providelo <cprov@canonical.com>

set -e
set -u

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

DESC="launchpad buildd sequencer"
NAME="buildd-sequencer"

LP=/srv/launchpad.net/codelines/current/
LPUSER="lp_buildd"
LPCONFIG="ftpmaster"

TWISTD="$LP/sourcecode/twisted/bin/twistd"
TACFILE="$LP/daemons/buildd-sequencer.tac"
PIDFILE="/var/run/buildd-sequencer/$LPCONFIG.pid"
LOGFILE="/var/log/buildd-sequencer/$LPCONFIG.log"


# Gracefully exit if the package has been removed.
test -e $TACFILE || exit 0


#
#       Function that starts a buildd slave
#
d_start() {
    # We cd to the launchpad root so we don't hold on to a random working
    # directory forever.
    CMD="cd $LP && PYTHONPATH=$LP/lib: LPCONFIG=$LPCONFIG $TWISTD --pidfile $PIDFILE --python $TACFILE --logfile $LOGFILE"
    if [ `whoami` = "$LPUSER" ]; then
        sh -c "$CMD"
        chmod +r $PIDFILE
    else
        su - $LPUSER -c "$CMD"
        su - $LPUSER -c "chmod +r $PIDFILE"
    fi
}

#
#       Function that stops a buildd slave
#
d_stop() {
    test -r $PIDFILE && kill -TERM $(cat $PIDFILE) || true
}


case "$1" in
  start)
        echo -n "Starting $DESC: $NAME"
	d_start
        echo "."
        ;;
  stop)
        echo -n "Stopping $DESC: $NAME"
	d_stop
        echo "."
        ;;
  restart|force-reload)
        #
        #       If the "reload" option is implemented, move the "force-reload"
        #       option to the "reload" entry above. If not, "force-reload" is
        #       just the same as "restart".
        #
	$0 stop
	sleep 1
	$0 start
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
